wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [36, 30, 55, 30, 30]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [10, 11, 11, 12, 4]
  refreshInterval: 1

  mods:

    ######
    github:
      apiKey: "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"
      baseURL: ""
      title: "GitHub"
      enabled: true
      enableStatus: true
      position:
        top: 3
        left: 3
        height: 1
        width: 2
      refreshInterval: 5m
      repositories:
        - "cerebnismus/freelance-armut"
        - "hiqermod/networkman"
      uploadURL: ""
      username: "cerebnismus"

    #######
    battery:
      type: power
      title: "⚡️ Battery"
      enabled: true
      position:
        top: 0
        left: 4
        height: 1
        width: 1
      refreshInterval: 15

    #########
    superbox:
      type: cmdrunner
      title: "superbox"
      args: ["/Users/macbook/Desktop/freelance-armut/python_tmp/superbox.py"]
      cmd: "python3"
      enabled: true
      position:
        top: 2
        left: 0
        height: 2
        width: 1
      refreshInterval: 900

    neofetch:
      type: cmdrunner
      title: "neofetch"
      cmd: "neofetch"
      enabled: true
      position:
        top: 1
        left: 1
        height: 2
        width: 2
      refreshInterval: 900

    #########
    resources:
      type: resourceusage
      title: "〰 Resource Usage"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 1

    ####
    news:
      type: hackernews
      title: "🚨 Hacker News"
      enabled: true
      numberOfStories: 10
      position:
        top: 3
        left: 1
        height: 1
        width: 2
      storyType: top
      refreshInterval: 1200
    
    ######
    ipinfo:
      title: "🕸  IP Information"
      colors:
        name: "lightblue"
        value: "yellow"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 900

    #############
    security_info:
      type: security
      title: "🔐 Security"
      enabled: true
      position:
        top: 1
        left: 4
        height: 1
        width: 1
      refreshInterval: 900

    ######
    uptime:
      type: cmdrunner
      args: []
      cmd: "uptime"
      title: "⏱  uptime"
      enabled: true
      position:
        top: 4
        left: 0
        height: 1
        width: 2
      refreshInterval: 30

    #############
    prettyweather:
        title: "🌦  Weather Report"
        enabled: true
        city: "Ankara"
        position:
            top: 0
            left: 1
            height: 1
            width: 1
        refreshInterval: 5m
        unit: "m"
        view: 0
        language: "en"

    ########
    yfinance:
      enabled: true
      title: "💵 Finance"
      sort: true
      refreshInterval: 5m
      symbols:
        - "ASELS.IS"
        - "NETAS.IS"
        - "TTKOM.IS"
        - "TCELL.IS"
        - "EURTRY=X"
        - "USDTRY=X"
        - "GBPTRY=X"
      position:
        top: 1
        left: 0
        height: 1
        width: 1

    ########
    textfile:
      enabled: false
      filePath: "~/.config/wtf/config.yml"
      format: true
      position:
        top: 1
        left: 0
        height: 4
        width: 1
      refreshInterval: 30
      wrapText: false
    
    #######
    spotify:
      title: "𝄢 Spotify"
      enabled: true
      colors:
        label: "red"
        text: "white"
      position:
        top: 2
        left: 4
        height: 1
        width: 1
      refreshInterval: 0

    ############
    digitalclock:
      withDatePrefix: False
      dateFormat: "Monday 02 Jan 2006"
      color: orange
      enabled: true
      font: digitalfont
      hourFormat: 24
      position:
        top: 0
        left: 3
        height: 1
        width: 1
      refreshInterval: 1s
      title: "big clock"
      type: "digitalclock"